version: "3.9"
services:

#< ----------------------- >

  proxy:

    container_name: kett_proxy

    hostname: kett_proxy

    build: ./proxy/.

    ports:
      - "80:80" # port for apis
      - "32662:32662"

    volumes:
      - ./proxy/conf/:/etc/nginx/conf.d
      - ./proxy/def_conf/:/etc/nginx/sites-available/:ro
      - ./proxy/def_conf/:/etc/nginx/sites-enabled/:ro
      - ./proxy/logs/:/var/log/nginx
      - ./proxy/certs:/certs:ro

    depends_on:
      - kett_backend

    restart: always

#< ----------------------- >

  kett_backend:

    container_name: kett_backend

    hostname: kett_backend

    build: ./application/.

    volumes:
      - ./application/:/kett_backend/:rw

    #environment:
      ## DEBUG
      #- DJANGO_DEBUG=${DJANGO_DEBUG}
      #- AUTH_OFF=${AUTH_OFF}
      ## SECRETS AND PASSWORDS
      #- DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      #- DJANGO_SALT=${DJANGO_SALT}
      #- DJANGO_SETTINGS_USERNAME=${DJANGO_SETTINGS_USERNAME}
      #- DJANGO_SETTINGS_PASSWORD=${DJANGO_SETTINGS_PASSWORD}
      #- DJANGO_USER_DB_USERNAME=${DJANGO_USER_DB_USERNAME}
      #- DJANGO_USER_DB_PASSWORD=${DJANGO_USER_DB_PASSWORD}
      #- DJANGO_CGAPDB_USERNAME=${DJANGO_CGAPDB_USERNAME}
      #- DJANGO_CGAPDB_PASSWORD=${DJANGO_CGAPDB_PASSWORD}
      #- DJANGO_LOGDB_USERNAME=${DJANGO_LOGDB_USERNAME}
      #- DJANGO_LOGDB_PASSWORD=${DJANGO_LOGDB_PASSWORD}

      ## SETTINGS
      #- DJANGO_SETTINGS_URI=${DJANGO_SETTINGS_URI}
      #- DJANGO_SETTINGS_DB_NAME=${DJANGO_SETTINGS_DB_NAME}
      #- DJANGO_SETTINGS_COLLECTION=${DJANGO_SETTINGS_COLLECTION}
      #- DJANGO_STATIC_SETTINGS_COLLETCTION=${DJANGO_STATIC_SETTINGS_COLLETCTION}


    ports: # keep commented in production!
      - "8000:5001" # keep commented in production!

    restart: always

#< ----------------------- >
