version: "3.9"
services:

#< ----------------------- >

  kett_proxy:

    container_name: kett_proxy

    hostname: kett_proxy

    build: ./proxy/.

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./proxy/conf/:/etc/nginx/conf.d
      - ./proxy/def_conf/:/etc/nginx/sites-available/:ro
      - ./proxy/def_conf/:/etc/nginx/sites-enabled/:ro
      - ./proxy/logs/:/var/log/nginx
      - ./proxy/certs:/certs:ro
      - ./application/app/static:/static:ro

    depends_on:
      - kett_backend

    restart: always

#< ----------------------- >

  kett_backend:

    container_name: kett_backend

    hostname: kett_backend

    build: ./application/.

    volumes:
      - ./application/:/kett_backend/:rw

    ports: # keep commented in production!
      - "8000:5001" # keep commented in production!

    restart: always

#< ----------------------- >
